**Exam2: MATH 425/625 Numerical Analysis**

**Ben Moss**

**Question 1:** Consider the following formula for approximating the the second derivative:

$$
f^{\prime\prime}(x_0) = \dfrac{f(x_0-h) - 2f(x_0) + f(x_0+h)}{h^2} - \dfrac{h^2}{12}f^{(4)}(\xi_0).
$$
Suppose that in evaluating $f(x_0-h)$, $f(x_0)$, and  $f(x_0 + h)$, we encounter round-off errors $e(x_0 - h)$, $e(x_0)$, and $e(x_0 + h)$. Assuming that the round-off errors are bounded by some number $\epsilon > 0$ and that the 4th derivative of $f$ is bounded by a number $M > 0$, in the interval $[x_0 - h, x_0 + h]$, analyze the round-off error in approximating $f^{\prime\prime}(x_0)$ and derive an upper bound. 



 

**Solution:** Suppose that in evaluating $f(x_0 - h)$, $f(x_0)$, and $f(x_0 + h)$, we encounter round-off errors $e(x_0 - h)$, e(x_0) and $e(x_0 + h).$ Then our computations actually use the values $\tilde{f}(x_0 - h)$, $\tilde{f}(x_0)$ and $\tilde{f}(x_0 + h)$ which are related to the true values $f(x_0 - h)$, $f(x_0)$, and $f(x_0 + h)$ by
$$f(x_0 - h)=\tilde{f}(x_0 - h)+e(x_0 - h)$$
$$2f(x_0)=2\tilde{f}(x_0)+e(x_0)$$
$$f(x_0 + h)=\tilde{f}(x_0 + h)+e(x_0 + h).$$ 

The total error in the approximation, 

$$f''(x_0)- \dfrac{\tilde{f}(x_0 - h)-2\tilde{f}(x_0)-\tilde{f}(x_0 + h)}{h^2}=\dfrac{e(x_0-h)-e(x_0)-e(x_0+h)}{h^2}-\dfrac{h^2}{12}f^{(4)}(\xi_0),$$

is due both to round-off error, the first part, and to truncation error. If we assume that the round-off errors $e(x_{0}\pm\,h)$ and $e(x_{0})$ are bounded by some number $\epsilon>0$ and that the fourth derivative of $f$ is bounded by a number $M>0$ then 

$$\bigg\lvert f''(x_0)- \dfrac{\tilde{f}(x_0 - h)-2\tilde{f}(x_0)-\tilde{f}(x_0 + h)}{h^2} \bigg\rvert\leq \bigg\lvert\dfrac{\epsilon}{h^2}-\dfrac{f^{(4)}(\xi_0)}{12}h^2\bigg\rvert $$

which in turn yields

$$\bigg\lvert f''(x_0)- \dfrac{\tilde{f}(x_0 - h)-2\tilde{f}(x_0)-\tilde{f}(x_0 + h)}{h^2} \bigg\rvert\leq 
\dfrac{\epsilon}{h^2}+\dfrac{f^{(4)}(\xi_0)}{12}h^2 \leq \dfrac{\epsilon}{h^2} + \dfrac{M}{12}h^2 .$$

This is our upper bound and our final answer. 


**Question 2:** A natural cubic spline $S$ on $[0,2]$ is defined by
\begin{align*}
S(x) &= S_0(x) = 1 + B(x-1) - D(x-1)^3, 1 \leq x < 2 \\
S(x) &= S_1(x) = 1 + b(x-2) - \frac{3}{4}(x-2)^2 + d(x-2)^3,  2 \leq x \leq 3
\end{align*} 
If $S$ interpolates the data $(1,1)$, $(2,1)$, $(3,0)$, find $B$, $D$, $b$, $d$.

**Solution:**

In [55]:
import numpy as np
import math
from scipy import linalg
import matplotlib.pyplot as plt
from scipy.interpolate import CubicSpline
import tensorflow as tf

In [56]:
x_grid = np.arange(1,4,1)
print(x_grid)

[1 2 3]


In [57]:
y_grid = [1, 1, 0]
print(y_grid)

[1, 1, 0]


In [58]:
h0 = x_grid[0] - x_grid[1]
h1 = x_grid[1] - x_grid[2]

In [59]:
print(h0)
print(h1)

-1
-1


In [60]:
ASpline = np.array([[1,0],
                  [0,1]])

In [61]:
print(ASpline)

[[1 0]
 [0 1]]


In [62]:
Yvec = np.array([[0],  
                 [0]])
print(Yvec)

[[0]
 [0]]


In [63]:
cvalues = linalg.solve(ASpline, Yvec)
print('c = \n', cvalues, '\n')

c = 
 [[0.]
 [0.]] 



In [64]:
cs = CubicSpline(x_grid, y_grid, bc_type = 'natural')

# S1 Polynomial coefficients
a0 = cs.c.item(3,0)
b0 = cs.c.item(2,0)
c0 = cs.c.item(1,0)
d0 = cs.c.item(0,0)

# S2 Polynomial coefficients
a1 = cs.c.item(3,1)
b1 = cs.c.item(2,1)
c1 = cs.c.item(1,1)
d1 = cs.c.item(0,1)

In [65]:
# Print polynomial equations for different x regions
print('S0(1<=x<2) = ', a0, ' + ', b0, '(x-1) + ', c0, '(x-1)^2  + ', d0, '(x-1)^3')
print('S1(2<= x<=3) = ', a1, ' + ', b1, '(x-2) + ', c1, '(x-2)^2  + ', d1, '(x-2)^3')

S0(1<=x<2) =  1.0  +  0.25000000000000006 (x-1) +  0.0 (x-1)^2  +  -0.25000000000000006 (x-1)^3
S1(2<= x<=3) =  1.0  +  -0.5000000000000001 (x-2) +  -0.7499999999999999 (x-2)^2  +  0.25 (x-2)^3


Therefore, our coefficients are $B=D=d=\dfrac{1}{4}$ and $b=-\dfrac{1}{2}.$

We can easily verify this by hand, we have 
$$S_{0}(1)=1+0.25(1-1)-0.25(1-1)^{3}=0,$$
$$S_{1}(2)=1-0.5(2-2)-0.75(2-2)^2+0.25(2-2)^3=1,$$
$$S_{1}(3)=1-0.5(3-2)-0.75(3-2)^2+0.25(3-2)^3=0.$$

Therefore, the result holds and these coefficients are the final answer. 



**Question 3:** Use the `TensorFlow` library to implement the *modified* Newton's method for finding the non-simple root (i.e., multiplicity $m > 1$) of $f(x) = e^x - x - 1$. You should use the build in functions for automatic differentiation in order to compute the derivatives. 


**Solution:** We begin by implementing Newton's modified algorithm to use as a basis for our code. We have 

In [66]:
def mnewton(f,Df,DDf,x0,epsilon,max_iter):
    '''Approximate solution of f(x)=0 utilizing Newton's modified method.

    Parameters
    ----------
    f : function
        Function for which we are searching for a solution f(x)=0.
    Df : function
        Derivative of f(x).
    DDf: function
        Derivative of Df
    x0 : number
        Initial guess for a solution f(x)=0.
    epsilon : number
        Stopping criteria is abs(f(x)) < epsilon.
    max_iter : integer
        Maximum number of iterations of Newton's method.

    Returns
    -------
    xn : number
        Implement Newton's modified algorithm: compute the linear approximation
        of f(x) at xn and find x intercept by the formula
            x = xn - f(xn)/Df(xn)
        Continue until abs(f(xn)) < epsilon and return xn.
        If Df(xn) == 0, return None. If the number of iterations
        exceeds max_iter, then return None.
        '''
    xn = x0
    for n in range(0,max_iter):
        fxn = f(xn)
        if abs(fxn) < epsilon:
            print('Found solution after',n,'iterations.')
            return xn
        Dfxn = Df(xn)
        if Dfxn == 0:
            print('Zero derivative. No solution found.')
            return None
        DDfxn = DDf(xn)
        if DDfxn == 0:
            print('Zero second derivative. No solution found.')
            return None
        xn = xn - (fxn*Dfxn)/(Dfxn**2-(fxn*DDfxn))
    print('Exceeded maximum iterations. No solution found.')
    return None

In [67]:
p = lambda x: math.exp(x) - x - 1
Dp = lambda x: math.exp(x) - 1
DDp = lambda x: math.exp(x)
approx = mnewton(p,Dp,DDp,1,1e-10,10)
print(approx)

Found solution after 3 iterations.
-1.1890183808588653e-05


Now we must use TensorFlow to define a few variables. 

In [68]:
x = tf.Variable((0.0), dtype=tf.float32)

In [69]:
with tf.GradientTape() as tape:
    y = tf.exp(x)-x-1

In [70]:
y_p = tape.gradient(y, x)

In [71]:
y_p.numpy()

0.0

In [72]:
with tf.GradientTape() as tape2:
    y_2 = tf.exp(x)-1

In [73]:
y_p2 = tape2.gradient(y_2, x)

In [74]:
y_p2.numpy()

1.0

In [75]:
with tf.GradientTape() as tape3:
    y_3 = tf.exp(x)

In [76]:
y_p3 = tape3.gradient(y_3, x)

In [77]:
y_p3.numpy()

1.0

We have found the local minimum of $f(x)=e^{x}-x-1$ is $f'(0)=e^{0}-1=0$, and thus $x=0$ is a local minimum of this function. 

By observation, since $f(x)=e^{x}-x-1$ is strictly decreasing over the interval $(-\infty,0]$ as $x\rightarrow0$ and $f(x)=e^{x}-x-1$ is strictly increasing over the interval $[0,\infty)$ as $x\rightarrow\infty$ we know that $x=0$ is also a global minimum.

Now we proceed with the Newton's modified method with TensorFlow. We have 

In [78]:
def mnewton2(f,Df,DDf,x0,epsilon,max_iter):
    '''Approximate solution of f(x)=0 utilizing Newton's modified method.

    Parameters
    ----------
    f : function
        Function for which we are searching for a solution f(x)=0.
    Df : function
        Derivative of f(x).
    DDf: function
        Derivative of Df
    x0 : number
        Initial guess for a solution f(x)=0.
    epsilon : number
        Stopping criteria is abs(f(x)) < epsilon.
    max_iter : integer
        Maximum number of iterations of Newton's method.

    Returns
    -------
    xn : number
        Implement Newton's modified algorithm: compute the linear approximation
        of f(x) at xn and find x intercept by the formula
            x = xn - f(xn)/Df(xn)
        Continue until abs(f(xn)) < epsilon and return xn.
        If Df(xn) == 0, return None. If the number of iterations
        exceeds max_iter, then return None.
        '''
    xn = x0
    for n in range(0,max_iter):
        fxn = y
        if abs(fxn) < epsilon:
            print('Found solution after',n+1,'iteration.')
            return xn
        Dfxn = y_p
        if Dfxn == 0:
            print('Zero derivative. No solution found.')
            return None
        DDfxn = y_p2
        if DDfxn == 0:
            print('Zero second derivative. No solution found.')
            return None
        xn = xn - (fxn*Dfxn)/(Dfxn**2-(fxn*DDfxn))
    print('Exceeded maximum iterations. No solution found.')
    return None

In [79]:
p = lambda x: y
Dp = lambda x: y_p
DDp = lambda x: y_p2
approx = mnewton2(y,y_p,y_p2,0,1e-10,10)
print(approx)

Found solution after 1 iteration.
0


The solution was found after one iteration because differentiation a single time is necessary to solve for the $0$ of the function. Therefore, $0$ is the solution to the zero of our function. 


**Question 4:** (Graduate Students): Suppose that $f:\mathbb{R}^n \rightarrow \mathbb{R}$ is given by $f(x) = x^T Q X$, where $Q$ is an $n \times n$ (symmetric) positive semidefinite matrix. Show that $f$ is convex.

**Proof:** Given $f:\mathbb{R}^n \rightarrow \mathbb{R}$ is defined by $f(x) = X^T Q X$, where $Q$ is an $n \times n$ (symmetric) positive semidefinite matrix, we will show that $f$ is convex. 

We will proceed directly by showing that
$$f(x_{2}+t(x_{1}-x_{2}))-tf(x_{1})-(1-t)f(x_{2})\leq0$$ 

for all $x_{1},\,x_{2}\in \mathbb{R}^{n}$ with $x_{1}\neq\,x_{2}$ and for all $t\in[0,1].$ If this parameterized inequality holds then this will prove $f$ is convex. We proceed with direct calculation. We have that the above inequality is equal to the following

\begin{align*}
(x_{2}^{T}+tx_{1}^{T}-tx_{2}^{T})(Qx_{2}+tQx_{1}-tQx_{2})-tx_{1}^{T}Qx_{1}-(1-t)x_{2}^{T}Qx_{2}&= \\
x_{2}^{T}Qx_{2}+tx_{2}^{T}Qx_{1}-tx_{2}^{T}Qx_{2}+tx_{1}^{T}Qx_{2}+t^{2}x_{1}^{T}Qx_{1}-t^{2}x_{1}^{T}Qx_{2}-tx_{2}^{T}Qx_{2}-t^{2}x_{2}^{T}Qx_{1}+t^{2}x_{2}^{T}Qx_{2} \\
-tx_{1}^{T}Qx_{1}-(1-t)x_{2}^{T}Qx_{2}&= \\
(1-2t+t^2-1+t)x_{2}^{T}Qx_{2}+(t^2-t)x_{1}^{T}Qx_{1}+(t+t-t^2-t^2)x_{2}^{T}Qx_{1} &=\\
(-2t+t^2+t)x_{2}^{T}Qx_{2}+(t^2-t)x_{1}^{T}Qx_{1}+(2t-2t^2)x_{2}^{T}Qx_{1} &=\\
(t^2-t)x_{2}^{T}Qx_{2}-2(t^2-t)x_{2}^{T}Qx_{1}+(t^2-t)x_{1}^{T}Qx_{1} &= \\
(t^2-t)\cdot(x_{1}-x_{2})^{T}Q(x_{1}-x_{2}).&
\end{align*}

The last line $(t^2-t)\cdot(x_{1}-x_{2})^{T}Q(x_{1}-x_{2})\leq 0$ because $(t^2-t)\leq0$ for all $t\in[0,1]$ and thus the result follows. $\blacksquare$